/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as AccountRouteImport } from './routes/_account/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppDashboardImport } from './routes/_app/dashboard'
import { Route as AccountRegisterImport } from './routes/_account/register'
import { Route as AccountLoginImport } from './routes/_account/login'

// Create/Update Routes

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AccountRouteRoute = AccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

const AccountRegisterRoute = AccountRegisterImport.update({
  path: '/register',
  getParentRoute: () => AccountRouteRoute,
} as any)

const AccountLoginRoute = AccountLoginImport.update({
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/_account/login': {
      id: '/_account/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AccountLoginImport
      parentRoute: typeof AccountRouteImport
    }
    '/_account/register': {
      id: '/_account/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AccountRegisterImport
      parentRoute: typeof AccountRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AccountRouteRouteChildren {
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountLoginRoute: AccountLoginRoute,
  AccountRegisterRoute: AccountRegisterRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/login': typeof AccountLoginRoute
  '/register': typeof AccountRegisterRoute
  '/dashboard': typeof AppDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/login': typeof AccountLoginRoute
  '/register': typeof AccountRegisterRoute
  '/dashboard': typeof AppDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_account': typeof AccountRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_account/login': typeof AccountLoginRoute
  '/_account/register': typeof AccountRegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/register' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/register' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_account'
    | '/_app'
    | '/_account/login'
    | '/_account/register'
    | '/_app/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_account",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_account": {
      "filePath": "_account/route.tsx",
      "children": [
        "/_account/login",
        "/_account/register"
      ]
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/dashboard"
      ]
    },
    "/_account/login": {
      "filePath": "_account/login.tsx",
      "parent": "/_account"
    },
    "/_account/register": {
      "filePath": "_account/register.tsx",
      "parent": "/_account"
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
