services:
  # NOTE: it doesn't seem like docker plays very nicely with vite
  # vite_server:
  #   build:
  #     dockerfile: client/vite.dockerfile
  #   ports:
  #     - "3000:3000"
  #   develop:
  #     watch:
  #       - path: ./client
  #         target: .
  #         action: sync+restart
  #         ignore:
  #           - node_modules
  #       - path: client/package.json
  #         action: rebuild
  api_server:
    image: rider
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/rider?sslmode=disable"
      JWT_SECRET: "supersecret"
      ENVIRONMENT: "development"
    develop:
      watch:
        - path: ./server
          action: rebuild
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rider
    ports:
      - "5432:5432"

