services:
  api_server:
    image: rider
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/rider?sslmode=disable"
      JWT_SECRET: "supersecret"
      ENVIRONMENT: "development"
    develop:
      watch:
        - path: ./server
          action: rebuild
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rider
    ports:
      - "5432:5432"

