// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	GivenName  string
	FamilyName string
	Email      string
	Password   string
}

type AccountBand struct {
	ID        int32
	AccountID sql.NullInt32
	BandID    sql.NullInt32
	CreatedAt time.Time
	UpdatedAt time.Time
	IsAdmin   bool
}

type Band struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
