// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Account struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	GivenName  string
	FamilyName string
	Email      string
	Password   string
}

type AccountBand struct {
	ID             int32
	AccountID      int32
	BandID         int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	AccountIsAdmin bool
}

type Band struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
